PyAr/PyZombis

- Lista06CodingBat.py
Ejercicios by Nick Parlante (CodingBat) traducidos al español
> Crear lista 06 de coding bat

- listapalabras.py
Sea la declaracion sobre la diversidad: 
*“The Python Software Foundation and the global Python community welcome and encourage participation by everyone. Our community is based on mutual respect, tolerance, and encouragement, and we are working to help each other live up to these principles. We want our community to be more diverse: whoever you are, and whatever your background, we welcome you.”*
Se debe generar una lista de palabras con el texto utilizando split(), a continuacion se debe crear una lista con las palabras que comiencen o terminan con una de las letras "python". Imprimir la lista resultante No olvidar remover los caracteres especiales y cuidado con las mayusculas y las minusculas
> Crear una lista con las palabras

- fumadores.py
Programa para calcular la reduccion de tiempo de vida de un fumador
Se pregunta la cantidad de cigarrillos fumados por dia y cuantos años ya fumo.
Se considera que un fumador pierda 10 minutos de vida por cada cigarrillo,
se calculará cuantos dias de vida perderá el fumador.
Se exibe el total en dias
> Reduccion de vida de un fumador

- poblacion.py
Suponiendo que la poblacion de un pais A se del orden de 80000 habitantes
con una tasa anual de crecimiento de 3% y que la poblacion de B sea de 200000
con una tasa de crecimiento de 1.5%
Se debe hacer un programa que calcule y escriba el numero de años necesarios
para que la poblacion del pais A sobrepase o iguale a la poblacion del pais B,
manteniendo las tasas de crecimiento
> Calculo de crecimiento de poblacion A vs B

- pi.py
Calculo del Valor de PI segun la formular
pi = 4/1 - 4/3 + 4/5 - 4/7 + ......
Se pasa por parametro la cantidad de iteraciones que se desea realizar.-
> Calculo del valor de PI

- _sources/lectures/TWP05.rst
Traduje del portugués al español "Variables y estructuras de datos"
* Todos los textos y los códigos están traducidos al español
* Solo faltarían las imágenes
* También habría que revisar que el código ejecute bien
> Traducción inicial primer capitulo

- _sources/lectures/TWP05.rst
- _sources/lectures/TWP10.rst
* Todos los textos y los códigos están traducidos al español
* Solo faltarían las imágenes
* También habría que revisar que el código ejecute bien
>  Traduje del portugués al español "Condiciones"

- _sources/lectures/TWP17.rst
* Todos los textos y los códigos están traducidos al español
* Solo faltarían las imágenes
* También habría que revisar que el código ejecute bien
>  Traduje del portugués al español "Lista"

- README.md
Vi algunos links rotos y solucione los mismos
> Solucionar links en el README

- .github/workflows/publish.yml
- .github/workflows/python-app.yml
Work in Progress / Request for Comments :-)
> Deploy artifacts to improve CI/CD 

- _sources/quiz/Quiz7.rst
Partially
Close #20 
Close  #7 
This PR adds:
- The statements of the assignments were changed to better understand them.
- New assignments to the quiz with its `unittest` to be automatically graded
> Add new assignments to quiz 7 and reformulated the questions

- _sources/lectures/TWP18.rst
This PR resolves #7 (partly):
- Changes to TWP18 lecture.
- Added a new exercise with minimal unit-test for automatic grading.
- Added better instructions for the final exercise, and also added unit-test in it.
> Added tests with unit test to exercises in lecture TWP18

- _sources/lectures/TWP05.rst
Close #22 (Partial)
This PR  adds:
- Change in the order of Lecture
- Translate from Portuguese phrases 
- Improve redaction of lecture
> Changes in the redaction, order and the translation on lecture TWP05

- _sources/quiz/Quiz9.rst
This PR fixes #76 
Should work alright by now.
> Fixxed mayor_extremo exercise

- .github/pull_request_template.md
This PR implement a task list that must be resolved before being allowed to merge
For more info see:
* https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/about-task-lists
* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
> Add default PR template with checklist

- tests/test_quiz1.py
This PR adds a test for quiz1 ex 1, with ``playwright``
https://user-images.githubusercontent.com/80920858/120872328-0539af00-c564-11eb-80a9-a3f557dc15f7.mov
> added test for quiz1 ex 1

- _sources/quiz/Quiz7.rst
- tests/test_quiz7.py
Close y-martinez/PyZombis#12.
There were functions names in English so they were translated.
The ids of exercises were changed to ``q7_#number``
The code was checked with ``flake8`` and ``black`` to resolve any problems of styling
> Refactor the Quiz 7 with tests

- .gitignore
- _sources/quiz/Quiz1.rst
- _sources/quiz/Quiz3.rst
- _sources/quiz/Quiz9.rst
- tests/test_quiz1.py
- tests/test_quiz3.py
This PR closes LeoCumpli21/PyZombis#20. I added subtitles to the exercises as agreed with my fellow collaborators.
Also, it closes LeoCumpli21/PyZombis#21. I modified quiz 3 to accomplish the accorded conventions, and I added a ``playwright`` test to it as well. 
https://user-images.githubusercontent.com/80920858/121257389-3e7b6300-c873-11eb-90ed-1591503a90d1.mp4
> Added subtitles to Quiz 1 and modified Quiz 3

- _sources/quiz/Quiz9.rst
- tests/test_quiz9.py
This PR closes LeoCumpli21/PyZombis#23 by:
1. Adding subtitles to each exercise (*Ejercicio #*)
2. Changing each activecode snippet's id to be *q9_#*
2. Translating variable and function names to Spanish and writing them in underscore notation.
3. Checking python code is PEP8 compliant with `flake8`.
4. Adding a playwright test for ex 1 (watch the attached video).
https://user-images.githubusercontent.com/80920858/121606853-87b6e880-ca14-11eb-8a91-643d24c6d09b.mp4
> Update quiz9 to follow conventions

- _sources/quiz/Quiz6.rst
- tests/test_quiz6.py
This PR closes LeoCumpli21/PyZombis#22 by:
1. Adding subtitles to each exercise as *Ejercicio #*
2. Changing each exercise's id to `q6_#`
3. Rewriting the instructions of each exercise so that they are comprehensible and the `rst` formatting doesn't mess up anything.
4. Making sure python code is PEP8 compliant. I used `flake8` for this.
5. Finally, I made a test with Playwright for ex 1 (see the attached video).
https://user-images.githubusercontent.com/80920858/121464567-b633b580-c979-11eb-9396-61de5dac92d5.mp4
> Update quiz 6 file to work appropriately

- _sources/quiz/Quiz5.rst
- tests/test_quiz5.py
> Refactor all the exercises of quiz 5

- _sources/quiz/Quiz11.rst
- tests/test_quiz11.py
This PR closes LeoCumpli21/PyZombis#24 by:
1. Adding subtitles and changing id's to each exercise.
2. Translating everything from Portuguese to Spanish.
3. Formatting Python code with `black` using `--line-length 120`.
4. Adding a web test for exercise 3.
https://user-images.githubusercontent.com/80920858/121787226-7f80b980-cb8a-11eb-9b46-b9619efdfcb0.mp4
> Translate quiz 11 and add test

- _sources/quiz/Quiz10.rst
- tests/test_quiz10.py
> Improve the quiz10 and test

- _sources/quiz/Quiz13.rst
- tests/test_quiz13.py
This PR closes LeoCumpli21/PyZombis#25 by:
1. Adding subtitles and correct ID's to each exercise.
2. Translating the whole file to Spanish.
3. Adding a `playwright` test and formatting with `black`.
https://user-images.githubusercontent.com/80920858/121946347-745c9380-cd1a-11eb-95c2-f41df52a5072.mp4
> Fix quiz 13 and add Playwright test

- _sources/quiz/Quiz12.rst
- tests/test_quiz12.py
This PR Close: y-martinez/PyZombis#16
> Improve the quiz12 with tests

- tests/test_quiz3.py
This PR closes LeoCumpli21/PyZombis#27 by making the test for quiz 3 less repetitive using a for loop.
https://user-images.githubusercontent.com/80920858/121936307-1aa29c00-cd0f-11eb-98a2-e83893d9b3e8.mp4
> Make test q3_2 less repetitive

- _sources/quiz/Quiz14.rst
- tests/test_quiz14.py
This PR Close: y-martinez/PyZombis#17
> Improve the quiz14 with tests

- _sources/quiz/QuizExtras2.rst
- tests/test_quizExtra2.py
This PR Close y-martinez/PyZombis#18
> Improve the quiz extra 2 and test

- _sources/quiz/QuizExtras.rst
- tests/test_quizExtra.py
This PR closes LeoCumpli21/PyZombis#26.
https://user-images.githubusercontent.com/80920858/122105310-3e80e300-cdde-11eb-9638-c2e11bccb3fd.mp4
> Translate Quiz Extras and add test

- _sources/quiz/Quiz2.rst
- tests/test_quiz2.py
This PR Close: y-martinez/PyZombis#14, adding all the exercises missing
> Add the exercises to Quiz 2

- _sources/index.rst
- _sources/quiz/Quiz4.rst
- tests/test_quiz4.py
This PR closes LeoCumpli21/PyZombis#4. 
I added Quiz 4, as it was missing. I implemented the exercises from this file: 
[Lista de Exercícios IV Python para Zumbis.pdf](https://github.com/PyAr/PyZombis/files/6672975/Lista.de.Exercicios.IV.Python.para.Zumbis.pdf)
I also made a web test for q4_1 with playwright.
https://user-images.githubusercontent.com/80920858/122466489-006ef500-cf7f-11eb-8cc8-63a9d9fde1f4.mp4
> Add quiz 4

- _sources/lectures/TWP15.rst
This PR closes LeoCumpli21/PyZombis#31.
**Note**: I didn't focus on changing redaction nor grammar.
> Update Repeticiones (TWP15) lecture

- _sources/lectures/TWP23.rst
- _sources/lectures/_static/alice.txt
- tests/test_TWP23.py
This PR closes LeoCumpli21/PyZombis#33. 
**Note**: I didn't focus on redaction nor grammar. 
*TODO*: The final exercise is missing ActiveCode. I haven't added it yet because the `.txt` file the exercise uses has more than 3000 lines.  
[alice.txt](https://github.com/PyAr/PyZombis/files/6688286/alice.txt)
**UPDATE**: I added the final exercise already. I added the `alice.txt`  file to _static, and referenced it in a datafile directive in the lecture.
https://user-images.githubusercontent.com/80920858/122974928-734de680-d358-11eb-8d9b-99004b0f6d47.mp4
> Refactor TWP23 lecture

- tests/test_quiz3.py
This PR closes LeoCumpli21/PyZombis#35. I made sure to restructure the test as @NicolasSandoval suggested here https://github.com/PyAr/PyZombis/pull/94#pullrequestreview-687846838
https://user-images.githubusercontent.com/80920858/122824351-23164c00-d2a6-11eb-9e0d-aaf68b485fc9.mp4
> Changed quiz3_2 test

- _sources/lectures/TWP18.rst
- tests/test_TWP18.py
This PR closes LeoCumpli21/PyZombis#32 by formatting all code with `black`. Also, I added a web test for activecode 5.
*Note*: I didn't focus on redaction nor grammar.
https://user-images.githubusercontent.com/80920858/122971114-4a2b5700-d354-11eb-8cf6-8f34cc8c1a64.mp4
> Format TWP18 and add test

- _sources/quiz/Quiz12.rst
Following the @NicolasSandoval suggestions, I reformulated the statement of exercise 2, now it is more understandable.
> Reformulated the exercise 2 on Quiz 12

- _sources/lectures/TWP45.rst
This PR closes LeoCumpli21/PyZombis#10. I added the Reddit exercise. It already existed. I just debugged it. There's no web test needed in here.
> Added Reddit exercise

- _sources/lectures/TWP25.rst
This PR close y-martinez/PyZombis#22
- The ``activecode`` in the lesson had problems of indentation, there were resolved
- Add a new example of OOP that was missing.
- The subtitles were changed.
- The ``ìds`` were changed.
> 22 lesson clases objetos TWP25

- _sources/lectures/TWP20.rst
This PR close y-martinez/PyZombis#21
- The title was changed because the older has a problem.
- The ids were changed following the ruleset.
> Lesson for, funciones y azar TWP20

- _sources/lectures/TWP33.rst
This PR close y-martinez/PyZombis#23
> Update the lesson of startbuzz TWP33

- _sources/lectures/TWP40.rst
This PR close y-martinez/PyZombis#25
- Add the missing text from the lesson.
- The ``ids`` were changed.
- Using the Brython module in order to use the ``eval()`` function not implemented in Sculpt. The output for the ``print`` doesn't show until the PR for @angelasofiaremolinagutierrez merged into the master branch of her RunestoneComponents repo
> Refactor all the lesson twp40

- _sources/quiz/Quiz2.rst
This PR close y-martinez/PyZombis#14
> Fix the exercises of quiz 2

- _sources/lectures/TWP45.rst
This PR closes LeoCumpli21/PyZombis#12.
* I added 2 exercises regarding a new API. 
* Also added the general concepts learned in this lecture.
> Add university domains API exercises

- _sources/lectures/TWP30.rst
This PR partially closes https://github.com/angelasofiaremolinagutierrez/PyZombis/issues/15 and resolves visual details left in https://github.com/PyAr/PyZombis/pull/117 
1. The color references is fixed. An html directive is used to highlight the code with the same colors on activecode blocks.
2. Repeated slides titles are deleted.
> Update lecture TWP30: Revisión general 1 (define colors)

- _sources/index.rst
This PR resolves https://github.com/angelasofiaremolinagutierrez/PyZombis/issues/19
- The section called: _Índices y tablas_ is removed
- An introduction video is inserted on top of the content menu. 
- The main title is centered
Note: This video is the Portuguese version of the introduction to the course. Once we have the video translated into Spanish, we can change the source of the video.
> Introduction video on index

- _sources/index.rst
- _sources/lectures/Reto01.rst
- tests/test_Reto01.py
This PR closes LeoCumpli21/PyZombis#13.
I implemented the Hangman game from the original course. I did it as a progressive exercise, where most activecodes need the previous ones to be completed before them to work appropriatly. 
* It is thought as being a challenge more than a simple exercise.
* It is a big test due to the fact that the activecodes are linked to each other with the `:include: ` parameter.
* In the video below, sometimes the screen seems to stall. This happens because the *dialog prompts* are being handled, but Playwright doesn't show this.
https://user-images.githubusercontent.com/80920858/126044041-6bc53309-b740-42dc-96ca-faaf01aa29e0.mp4
> Add Hangman challenge

- _sources/lectures/TWP45.rst
This PR closes LeoCumpli21/PyZombis#43.
A proxy now stands in all exercises. Let me know whether this works for you as well.
> Add proxy to exercises all exercises

- _sources/challenges/Reto02.rst
- tests/test_Reto02.py
This PR closes LeoCumpli21/PyZombis#42.
https://user-images.githubusercontent.com/80920858/127197114-1eeed728-6f90-4041-8f63-772c7f6981d2.mp4
> Final exercise of Pergamino challenge

- _sources/lectures/TWP23/TWP23_1.rst
- _sources/lectures/TWP23/TWP23_2.rst
- _sources/lectures/TWP23/TWP23_3.rst
- _sources/lectures/TWP23/TWP23_4.rst
This PR closes LeoCumpli21/PyZombis#46. This changes were inspired by @NicolasSandoval suggestions.
> Modify TWP23 instructions 

- _sources/quiz/Quiz1.rst
- tests/test_quiz1.py
This PR partially solves LeoCumpli21/PyZombis#48 and closes LeoCumpli21/PyZombis#49.
I changed the structure of quiz 1 to be similar to the challenges structure, using the `tabbed` directive. @NicolasSandoval Let me know if it's okay.
* I formatted the quiz 1 file with `black`, with `--line-lenght = 119`
* Its test was modified also.
https://user-images.githubusercontent.com/80920858/128069738-65348fff-8c67-4d10-8ff7-11277aa10ff1.mp4
https://user-images.githubusercontent.com/80920858/128069729-11f8d0e3-1da0-4707-afca-434b36f981f1.mp4
> Change quiz 1 structure

- tests/test_TWP18.py
This PR closes LeoCumpli21/PyZombis#53.
The same commands structure as in #168 was applied for the TWP18 test. 
https://user-images.githubusercontent.com/80920858/128408807-af6d4b60-2921-48af-ac65-f890e84a1f21.mp4
> new test structure for TWP18

- _sources/lectures/TWP50.rst
Add more information to the lesson, now it explains the difference between browser interfaces, desktop interfaces, and mobile interfaces, also I add a new dialogs configuration to move them to the initial position in the upper left corner
> Add more context information and the initial position of dialogs

- _sources/quiz/Quiz3.rst
- tests/test_quiz3.py
This PR is similar to #160
This PR closes LeoCumpli21/PyZombis#55
and also solves LeoCumpli21/PyZombis#48 partially
https://user-images.githubusercontent.com/80920858/128774112-0f1d5c8a-51f3-4670-84c8-391031496fb7.mp4
> Change quiz 3 structure

- _sources/quiz/Quiz4.rst
- _sources/quiz/Quiz5.rst
This PR is similar to #160
This PR closes LeoCumpli21#58
and also solves LeoCumpli21#48 partially
https://user-images.githubusercontent.com/80920858/128942193-2caa8591-5c6c-4882-8c05-35449dfc84cd.mp4
> Change quiz 5 structure

- _sources/quiz/Quiz6.rst
This PR closes LeoCumpli21#59
It also closes LeoCumpli21#48 partially
> Change quiz 6 structure 

- _sources/quiz/Quiz7.rst
This PR closes LeoCumpli21#60
It also closes LeoCumpli21#48 partially
Some formating was applied with `back`
> Change q7 structure

- _sources/quiz/Quiz9.rst
This PR closes LeoCumpli21#62
It also closes LeoCumpli21#48 partially
> Changed q9 structure using tabbed directive

- _sources/quiz/Quiz11.rst
- tests/test_quiz11.py
This PR closes LeoCumpli21#63
It also solves LeoCumpli21#48 partially
> Change quiz 11 structure

- _sources/quiz/Quiz12.rst
This PR closes LeoCumpli21#64
It also solves LeoCumpli21#48
> Change q12 structure using tabbed directive

- _sources/quiz/Quiz13.rst
This PR closes LeoCumpli21#65
It also solves LeoCumpli21#48
> Changed q13 structure using tabbed directive

- _sources/quiz/Quiz14.rst
This PR closes LeoCumpli21#66
It also solves LeoCumpli21#48
> Change q14 structure

- _sources/quiz/QuizExtras.rst
- tests/test_quizExtra.py
This PR closes LeoCumpli21#67
and also solves LeoCumpli21#48 partially
> Change qExtra1 structure

- _sources/quiz/QuizExtras2.rst
- tests/test_quizExtra2.py
This PR closes LeoCumpli21#68
and also solves LeoCumpli21#48 partially
> Change qExtra2 structure

- _sources/challenges/Reto01.rst
- _sources/challenges/Reto02.rst
- tests/test_Reto01.py
- tests/test_Reto02.py
> Change exercises titles in challenges

- requirements.txt
This PR makes a minor change in the **requirements.txt** file that was causing error with **runestone installation**.
> Update runestone install repo link

- _sources/lectures/TWP42/TWP42_2.rst
This PR adds **TWP42_2 : Conceptos básicos de SQL**, among the interactive lectures. This lecture aims at teaching the basic of sql like creating and loading tables.
> Refactored TWP42_2 : Conceptos básicos de SQL

- tests/test_TWP42.py
This PR adds E2E tests with playwright for the SQL lectures.
> SQL E2E tests with playwright

- tests/test_TWP60.py
This PR adds E2E for all the Pygame lectures.
> Added playwright tests for Pygame lectures

- _sources/lectures/TWP30/TWP30_2.rst
Added Parson exercise using the Parson Runestone Component. Fixes Issue #243.
> Added Parson exercise in TWP30_2 lecture

- _sources/lectures/TWP05/TWP05_2.rst
(short description of what does this PR, Issue #, etc.)
> Translating the second section to English

- docker-compose.yml
- skaffold.yaml
Add docker-compose and skafford configuration files as part of automating docker image build
> Add Docker-compose and Skafford configuration files

- _sources/lectures/TWP10/TWP10_7.rst
Added missing activecode examples
> Added missing activecode examples

- _sources/lectures/TWP10/TWP10_3_en.rst
- _sources/lectures/TWP10/TWP10_7_en.rst
- translator.py
This pull request contains two translations of lectures to English as well as the script used to make the translations.
> Two lectures translated to English using a script and the script 

- _sources/lectures/TWP10/TWP10_3_en.rst
Changes to correct Restructured Text formatting issue
> Changes to correct Restructured Text formatting issue

- _sources/lectures/TWP05/TWP05_10_en.rst
- _sources/lectures/TWP05/TWP05_11_en.rst
- _sources/lectures/TWP05/TWP05_12_en.rst
- _sources/lectures/TWP05/TWP05_13_en.rst
- _sources/lectures/TWP05/TWP05_16_en.rst
- _sources/lectures/TWP05/TWP05_4_en.rst
- _sources/lectures/TWP05/TWP05_8_en.rst
- _sources/lectures/TWP05/TWP05_9_en.rst
- _sources/lectures/TWP10/TWP10_3_en.rst
- _sources/lectures/TWP42/TWP42_1.rst
- _sources/lectures/TWP42/TWP42_1_en.rst
- _sources/lectures/TWP42/TWP42_2_en.rst
- _sources/lectures/TWP42/TWP42_3_en.rst
- clean_up.py
Add script to appends language suffix to IDs to avoid duplicate error and fix the duplicate IDs for the initial lectures.
> Add script to correct duplicate IDs

- _sources/challenges/Reto01_en.rst
- _sources/challenges/Reto03_en.rst
- _sources/quiz/Quiz10_en.rst
- _sources/quiz/Quiz11_en.rst
- _sources/quiz/Quiz12_en.rst
- _sources/quiz/Quiz13_en.rst
- _sources/quiz/Quiz1_en.rst
- _sources/quiz/Quiz2_en.rst
- _sources/quiz/Quiz3_en.rst
- _sources/quiz/Quiz4_en.rst
- _sources/quiz/Quiz5_en.rst
- _sources/quiz/Quiz6_en.rst
- _sources/quiz/Quiz7_en.rst
- _sources/quiz/Quiz8_en.rst
- _sources/quiz/Quiz9_en.rst
- _sources/quiz/QuizExtras2_en.rst
- _sources/quiz/QuizExtras_en.rst
(This PR adds quizzes and challenges to the translations with the Reto02.rst file excluded for auto translations.)
> Add more translations of English

- requirements.txt
- tests/test_TWP42.py
active code changes that facilitate progress saving
Solves the issue #251 
- Before clicking Save & Run
- After Save & Run
- Video of the process:
> Saving progess using local storage

- _sources/lectures/TWP05/TWP05_5_en.rst
- _sources/lectures/TWP05/TWP05_7_en.rst
- _sources/lectures/TWP15/TWP15_1_en.rst
- _sources/lectures/TWP15/TWP15_4_en.rst
- _sources/lectures/TWP18/TWP18_7_en.rst
- _sources/lectures/TWP23/TWP23_1_en.rst
- _sources/lectures/TWP23/TWP23_2_en.rst
- _sources/lectures/TWP23/TWP23_3_en.rst
- _sources/lectures/TWP30/TWP30_2_en.rst
- _sources/lectures/TWP33/TWP33_2_en.rst
- _sources/lectures/TWP37/TWP37_2_en.rst
- _sources/lectures/TWP37/TWP37_3_en.rst
- _sources/lectures/TWP37/TWP37_5_en.rst
- _sources/lectures/TWP37/TWP37_6_en.rst
This PR solves, 
- Backtick issues
- NO_BREAK_SPACE issues
- duplicate IDS for datafiles in en locale issues
- **Before**
- **After**
- **Before**
- **After**
- **Before**
- **After**
> No break space, backtick and duplicate ids for datafiles

- _sources/lectures/TWP15/TWP15_3.rst
Enable CodeLens button for loop lesson #236
> Remove CodeLens for activity

- _sources/lectures/TWP30/TWP30_5.rst
- _sources/lectures/TWP30/TWP30_6.rst
- tests/test_TWP30.py
Solves issue #210 
Removed HTML based code and added simple code
Added E2E tests
> simplified activity and added E2E tests
